package com.syed.core;

public enum Test {
//    SINGLE_LINE,
//    SINGLE_LINE_CASE_SENSITIVE,
//    SINGLE_LINE_EXACT,
//    SINGLE_LINE_CASE_SENSITIVE_EXACT,
//    MULTI_LINE,
//    MULTI_LINE_CASE_SENSITIVE,
//    MULTI_LINE_EXACT,
//    MULTI_LINE_CASE_SENSITIVE_EXACT

    EXACT,
    NON_EXACT,
    EXACT_CASE_SENSITIVE,
    NON_EXACT_CASE_SENSITIVE
}
